### PR TITLE
Updated email regex to support plus and period in middle

### PR DESCRIPTION
**Pull request by haidalinda**
I found the previous regex did not cover including a `+` symbol in the email (e.g. user+20@prolificinteractive.com) - updated to the Swift regex example found at http://emailregex.com

### CODE REVIEW

**Comment by ThibaultKlein** [comment]
Hey @hkellaway, thanks for the pull request, but the tests are failing. Can you push an update to have all the tests pass?

**Comment by haidalinda** [comment]
have yet to find a proper regex

**Comment by haidalinda** [comment]
@ThibaultKlein updated this to support plus and period in middle of email (e.g. `user+1@prolificinteractive.com` and `first.last@prolificinteractive.com`

**Comment by haidalinda** [comment]
@ThibaultKlein Travis isn't failing because of tests but because of verbose output. i recall you knew how to fix that - added you as a collaborator on my fork if you care to push to it in my absence

**Comment by ThibaultKlein** [comment]
Thanks for the update @hkellaway, I fixed the issue. You have to add `--silent` option to `pod repo update`

**Pull request merged**
